import { Party } from '@daml/types';

// These types would be generated by `dpm codegen-js` or `dpm codegen-alpha-typescript`.
// We are assuming their structure for this service file. The actual import path may
// vary based on your project setup and the `name` property in `daml.yaml`.
import { Invoice } from '../daml.js/canton-invoice-factoring-0.1.0/lib/Invoice';
import { Bid } from '../daml.js/canton-invoice-factoring-0.1.0/lib/Bid';
import { Advance } from '../daml.js/canton-invoice-factoring-0.1.0/lib/Advance';

// Argument types for choices.
// In a real project, these would also be imported from the generated code.
export interface PlaceBidArgs {
  factor: Party;
  advanceRate: string; // Daml.Numeric, serialized as string
  discountFee: string; // Daml.Numeric, serialized as string
}

export interface AcceptBidArgs {
  // This choice might require confirming details, e.g., a bank account ID for settlement.
  settlementAccountId: string;
}

export interface RepayArgs {
  // This choice likely has no arguments from the buyer's side.
  // The repayment amount is determined by the contract state.
}


// The base URL for the Canton participant's JSON API.
// In a real application, this should come from environment variables.
const ledgerUrl = process.env.REACT_APP_LEDGER_URL || 'http://localhost:7575';

/**
 * Represents an active contract returned from the JSON API query endpoint.
 */
export interface ActiveContract<T> {
  contractId: string;
  templateId: string;
  payload: T;
  signatories: Party[];
  observers: Party[];
  agreementText: string;
}

/**
* Represents the result of a successful API request.
*/
interface ApiResponse<T> {
  status: 200;
  result: T;
  warnings: any | null;
}

/**
* Represents the result of a failed API request.
*/
interface ApiErrorResponse {
  status: number;
  errors: string[];
  warnings: any | null;
}

/**
 * A generic helper function to make requests to the JSON API.
 * @param endpoint The API endpoint to call (e.g., '/v1/create').
 * @param token The JWT token for authentication.
 * @param method The HTTP method.
 * @param body The request body.
 * @returns The 'result' field from the JSON API response.
 */
const apiRequest = async <T>(
  endpoint: string,
  token: string,
  method: 'GET' | 'POST' = 'POST',
  body?: object
): Promise<T> => {
  const headers = {
    'Authorization': `Bearer ${token}`,
    'Content-Type': 'application/json',
  };

  const response = await fetch(`${ledgerUrl}${endpoint}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error(`API request failed: ${response.status} ${response.statusText}`, errorText);
    throw new Error(`API request failed: ${response.status} ${response.statusText} - ${errorText}`);
  }

  const jsonResponse: ApiResponse<T> | ApiErrorResponse = await response.json();

  if (jsonResponse.status !== 200) {
    const error = jsonResponse as ApiErrorResponse;
    console.error('API returned a non-200 status:', error.errors);
    throw new Error(`API error: ${error.errors.join(', ')}`);
  }

  return (jsonResponse as ApiResponse<T>).result;
};

// =============================================================================
// COMMANDS (Create / Exercise)
// =============================================================================

/**
 * Creates a new invoice on the ledger.
 * @param token The party's JWT token.
 * @param invoicePayload The payload for creating the Invoice contract.
 * @returns The result of the create command.
 */
export const createInvoice = (token: string, invoicePayload: Invoice) => {
  return apiRequest<ActiveContract<Invoice>>('/v1/create', token, 'POST', {
    templateId: 'Invoice:Invoice',
    payload: invoicePayload,
  });
};

/**
 * Places a bid on an existing invoice.
 * @param token The factor's JWT token.
 * @param invoiceCid The ContractId of the Invoice to bid on.
 * @param bidArgs The arguments for the PlaceBid choice.
 * @returns The result of the exercise command.
 */
export const placeBid = (token: string, invoiceCid: string, bidArgs: PlaceBidArgs) => {
  return apiRequest<any>('/v1/exercise', token, 'POST', {
    templateId: 'Invoice:Invoice',
    contractId: invoiceCid,
    choice: 'PlaceBid',
    argument: bidArgs,
  });
};

/**
 * Accepts a bid from a factor, creating an Advance contract.
 * @param token The supplier's JWT token.
 * @param bidCid The ContractId of the Bid to accept.
 * @param acceptArgs The arguments for the AcceptBid choice.
 * @returns The result of the exercise command.
 */
export const acceptBid = (token: string, bidCid: string, acceptArgs: AcceptBidArgs) => {
  return apiRequest<any>('/v1/exercise', token, 'POST', {
    templateId: 'Bid:Bid',
    contractId: bidCid,
    choice: 'AcceptBid',
    argument: acceptArgs,
  });
};

/**
 * Repays an advance, which completes the factoring cycle.
 * Called by the buyer upon invoice maturity.
 * @param token The buyer's JWT token.
 * @param advanceCid The ContractId of the Advance to repay.
 * @param repayArgs The arguments for the Repay choice (may be empty).
 * @returns The result of the exercise command.
 */
export const repayAdvance = (token: string, advanceCid: string, repayArgs: RepayArgs = {}) => {
  return apiRequest<any>('/v1/exercise', token, 'POST', {
    templateId: 'Advance:Advance',
    contractId: advanceCid,
    choice: 'Repay',
    argument: repayArgs,
  });
};


// =============================================================================
// QUERIES
// =============================================================================

/**
 * Fetches all invoices visible to the party associated with the token.
 * @param token The party's JWT token.
 * @returns A promise that resolves to an array of active Invoice contracts.
 */
export const getInvoices = (token: string) => {
  return apiRequest<ActiveContract<Invoice>[]>('/v1/query', token, 'POST', {
    templateIds: ['Invoice:Invoice'],
  });
};

/**
 * Fetches all bids visible to the party associated with the token.
 * For a specific invoice, filter the results client-side by `bid.payload.invoiceCid`.
 * @param token The party's JWT token.
 * @returns A promise that resolves to an array of active Bid contracts.
 */
export const getBids = (token: string) => {
  return apiRequest<ActiveContract<Bid>[]>('/v1/query', token, 'POST', {
    templateIds: ['Bid:Bid'],
  });
};

/**
 * Fetches all advances visible to the party associated with the token.
 * @param token The party's JWT token.
 * @returns A promise that resolves to an array of active Advance contracts.
 */
export const getAdvances = (token: string) => {
  return apiRequest<ActiveContract<Advance>[]>('/v1/query', token, 'POST', {
    templateIds: ['Advance:Advance'],
  });
};